### ISSUE TITLE
Required bricklets

### ISSUE THREAD

**Issue by davidoc85** [tyrrellsystems/node-red-contrib-tinkerforge#10]
Additionally we need the following bricklets:
- Industrial Dual Analog In
- Dual Relay Bricklet

**Comment by hardillb** [comment]
First passes on both these bricklets now checked in and published to NPM please test as soon as possible

**Comment by davidoc85** [comment]
Just tried to add the dual analogue in, however the poll interval is not appearing.  After loading it into the flow, it crashed with the following report:

`17 Nov 13:47:36 - ReferenceError: idai is not defined
    at null.<anonymous> (/home/tf/.node-red/node_modules/node-red-contrib-tinkerforge/bricklets/IndDualAnalogIn.js:47:11)
    at wrapper [as _onTimeout] (timers.js:258:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
`

**Comment by hardillb** [comment]
New version published, please try again

**Comment by davidoc85** [comment]
This time as soon as it was going to get a value back it exited with an exception, even though the topic is V/1:

`17 Nov 14:21:49 - [red] Uncaught Exception:
17 Nov 14:21:49 - ReferenceError: topic is not defined
    at Object.returnCB (/home/tf/.node-red/node_modules/node-red-contrib-tinkerforge/bricklets/IndDualAnalogIn.js:49:21)
    at IPConnection.eval (eval at <anonymous> (/home/tf/.node-red/node_modules/node-red-contrib-tinkerforge/node_modules/tinkerforge/lib/IPConnection.js:902:23), <anonymous>:1:43)
    at IPConnection.handleResponse (/home/tf/.node-red/node_modules/node-red-contrib-tinkerforge/node_modules/tinkerforge/lib/IPConnection.js:902:18)
    at IPConnection.handlePacket (/home/tf/.node-red/node_modules/node-red-contrib-tinkerforge/node_modules/tinkerforge/lib/IPConnection.js:973:18)
    at IPConnection.handleIncomingData (/home/tf/.node-red/node_modules/node-red-contrib-tinkerforge/node_modules/tinkerforge/lib/IPConnection.js:326:18)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:748:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:410:10)
    at emitReadable (_stream_readable.js:406:5)
    at readableAddChunk (_stream_readable.js:168:9)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:528:21)
`

**Comment by hardillb** [comment]
0.0.16 pushed with fix

**Comment by davidoc85** [comment]
Setup topics as V/1 and V/2 for each input, however the payload is giving the same result as it is moving the topic as V/1/1 and V/2/1, see debug below:

Also is the value supposed to be divided by1000000?  The real voltage is 3.67V

`17/11/2016, 16:07:31Vel1V/1/1 : msg.payload : number3678000

17/11/2016, 16:07:31Vel2V/2/1 : msg.payload : number3678000`

Dual Relay is good so far

**Comment by hardillb** [comment]
The node outputs 2 messages for each poll interval. The first is the reading from input 1 and will have "/1" added to the topic prefix. The second message is the reading from input 2 and will have "/2" added to the end. You should only have one instance of this node per bricklet.

I have fixed the / 1000 problem

**Comment by davidoc85** [comment]
Tried to separate the analogue values as I am only getting back one value on the debug as /1.
Only one value is coming back with the output:

```
17/11/2016, 17:04:20Vel1/1 : msg.payload : number0.002
17/11/2016, 17:04:25Vel1/1 : msg.payload : number0.002
```

See the following example for separating topic attached values

> [{"id":"559ce3db.62030c","type":"debug","z":"848f8973.2e01b8","name":"Vel1","active":true,"console":"false","complete":"payload","x":529,"y":104,"wires":[]},{"id":"46afba98.36dc44","type":"TinkerForge IndDualAnalogIn","z":"848f8973.2e01b8","device":"d84dd060.29f838","sensor":"wuE","pollTime":"5","name":"Velocity","topic":"","x":154.5,"y":112,"wires":[["6e228081.70b0b"]]},{"id":"6e228081.70b0b","type":"switch","z":"848f8973.2e01b8","name":"","property":"topic","propertyType":"msg","rules":[{"t":"eq","v":"/1","vt":"str"},{"t":"eq","v":"/2","vt":"str"}],"checkall":"true","outputs":2,"x":368.5,"y":123,"wires":[["559ce3db.62030c"],["cab55232.2cf568"]]},{"id":"cab55232.2cf568","type":"debug","z":"848f8973.2e01b8","name":"Vel2","active":true,"console":"false","complete":"payload","x":529,"y":140,"wires":[]},{"id":"d84dd060.29f838","type":"TinkerForgeConfig","z":"","host":"localhost","port":"4223","name":""}]

**Comment by hardillb** [comment]
The switch node stuff looks fine.

All I can think is that the second call is failing because there is a on going read for the first value. I will look in the morning to see if I can make them sequential

**Comment by hardillb** [comment]
I've just pushed version 18 which uses a different approach to read both values, can you give it a try

**Comment by davidoc85** [comment]
This time it takes a while to poll the points compared to the ptc bricklet. I think only when it detects a change in voltage.   The output otherwise looks the same.  Do you want to connect here to have a look at it?  Enabling some debugs as well might help.

`18/11/2016, 12:39:48Vel/1 : msg.payload : number0.001`
`18/11/2016, 12:39:53Vel1/1 : msg.payload : number3.68`
`18/11/2016, 12:39:53Vel/1 : msg.payload : number3.68`
`18/11/2016, 12:39:58Vel1/1 : msg.payload : number0.002`
`18/11/2016, 12:39:58Vel/1 : msg.payload : number0.002`

**Comment by hardillb** [comment]
Yes the change will now only output if the voltage has changed since last time at the moment. I could probably make it save the state and output it at the poll interval so it's consistent with the other types of nodes

**Comment by davidoc85** [comment]
Yeah if we can make it "poll" on a set basis as the other ones, that would be great.

**Comment by hardillb** [comment]
This is what we just fixed, it should now poll on the given interval even if the value does not change

**Comment by davidoc85** [comment]
Ok, I have tested it and looks good now, I think we can close this now.
