### ISSUE TITLE
Tinkerforge does not remember UID

### ISSUE THREAD

**Issue by davidoc85** [tyrrellsystems/node-red-contrib-tinkerforge#11]
This has not been easy to spot, however when I go home, stop the node and restart it the next morning the tinkerforge does not seem to remember the UID of the bricklet it was connected to when there are more of the same type and it defaults to the first one.  Once I change it works, however afterwards it is difficult to tell where it is connected to, as when a tinkerforge node is opened it always shows the first UID on the list as default.

**Comment by hardillb** [comment]
I'm out of the office all day today, but if that's the case it wouldn't
remember then over a restart of node-red either which I've not seen.

**Comment by hardillb** [comment]
I've only got one stack with 2 copies of the same bricklet type so it's hard to notice. But I've tracked it down

**Comment by davidoc85** [comment]
Check when you open the settings tab, the node defaults to the first one and does not show where it is connected.
