### ISSUE TITLE
Race condition between first message and connecting to bricklet

### ISSUE THREAD

**Issue by hardillb** [tyrrellsystems/node-red-contrib-tinkerforge#12]
See https://github.com/tyrrellsystems/node-red-contrib-simple-weekly-scheduler/issues/7 for details

**Comment by hardillb** [comment]
There is a fix for this in the last pull request merged. I've just pushed a new version to npm, @davidoc85 please test this.

**Comment by hardillb** [comment]
@davidoc85 can you test this so I can close this out please

**Comment by davidoc85** [comment]
Tested it and have no more error messages now by using the schedule
