### ISSUE TITLE
Ind Analogue out not updating

### ISSUE THREAD

**Issue by davidoc85** [tyrrellsystems/node-red-contrib-tinkerforge#15]
I came across an issue where the Ind Analogue Out is not updating when it is connected to the attached logic.  When the inject is directly connected to it, it works Ok.   Note: This is the 3rd Analogue out connected to a  second Master brick.  Any ideas why this might be?

[analogueout.txt](https://github.com/tyrrellsystems/node-red-contrib-tinkerforge/files/595566/analogueout.txt)

See debug:
```
16 Nov 19:25:17 - [info] [debug:FSpeedResult] 4  
16 Nov 19:25:47 - [info] [debug:FSpeedResult] 4  
16 Nov 19:26:17 - [info] [debug:FSpeedResult] 4  
16 Nov 19:26:48 - [info] [debug:FSpeedResult] 4  
16 Nov 19:27:18 - [info] [debug:FSpeedResult] 4  
16 Nov 19:27:48 - [info] [debug:FSpeedResult] 4 
```

**Comment by hardillb** [comment]
Can you add a screen shot of the flow

**Comment by davidoc85** [comment]
I have attached the export in github
[image: Inline images 1]

[image: Inline images 2]

**Comment by hardillb** [comment]
Those images didn't make it into the issue. You will have to drag them into the web page for them to exist.

Looking at the code the most likely reason for it not updating is because the payload you are passing in is not a number, but a string representation of the number

**Comment by hardillb** [comment]
Yep, the output from your subflow is a string "4" not the number 4

**Comment by hardillb** [comment]
This is a bug in the toggle node, just pushed a fix
