### ISSUE TITLE
Ind Digital In

### ISSUE THREAD

**Issue by davidoc85** [tyrrellsystems/node-red-contrib-tinkerforge#21]
Can we add a request on startup to send the values of each input, as at the moment is not picking up if the panel is in fault or fire after restart / re-deployment.

**Comment by hardillb** [comment]
probably, I'll have a look

**Comment by hardillb** [comment]
ok, done, I'll add it to the next push

**Comment by davidoc85** [comment]
Have installed the latest update, however when starting node-red quits with the following exception:

```
18 Nov 16:21:00 - [red] Uncaught Exception:                                     
18 Nov 16:21:00 - TypeError: Cannot call method 'getValue' of undefined         
    at Object.0 (/home/tf/.node-red/node_modules/node-red-contrib-tinkerforge/br
icklets/IndDigital4In.js:84:23)                                                 
    at IPConnection.handleConnect (/home/tf/.node-red/node_modules/node-red-cont
rib-tinkerforge/node_modules/tinkerforge/lib/IPConnection.js:302:70)            
    at Socket.emit (events.js:117:20)                                           
    at Object.afterConnect [as oncomplete] (net.js:886:10)`                      
`tf@fcu-6:~/.node-red$ npm list node-red-contrib-tinkerforge                     
/home/tf/.node-red                                                              
└── node-red-contrib-tinkerforge@0.0.19                                         
```

**Comment by hardillb** [comment]
ok, I know the problem is, a small typo

Look on line 84 of /home/tf/.node-red/node_modules/node-red-contrib-tinkerforge/br
icklets/IndDigital4In.js

change `node.ida4` to `node.idi4`

I'll do a fix, but if you can test it your end to be sure

**Comment by davidoc85** [comment]
Ok that worked on my end, however only the "true" states are working at the moment, if the input is false it does not give anything.  I think it is necessary to add it if possible.

**Comment by hardillb** [comment]
At start up or for all changes?

**Comment by davidoc85** [comment]
Only at startup, once the state changes it works fine.

**Comment by hardillb** [comment]
0.0.22 published which should push false state for low pins on startup
