### ISSUE TITLE
Node Red Analogue Out 2

### ISSUE THREAD

**Issue by mtoko** [tyrrellsystems/node-red-contrib-tinkerforge#23]
I have brickd running on a Pi with a Master Brick and Analogue Out v2 connect on port D connected to the Pi by USB. I am trying to control from Node Red and have installed node-red-contrib-tinkerforge. Brickviewer on the Pi can detect the master and analogue bricklet and can adjust the output correctly, so brickd seems to be working. Node red Analogue out node detects the Analogue node id correctly but does not change the output. The config is localhost:4223 which is the same as Brickviewer on the Pi.

The node-red-contrib-tinkerforge seems to be installed correctly the path is
/home/pi/.node-red/node_modules/node-red-contrib-tinkerforge

The example flow is simple

[{"id":"90bc3a09.d01ec8","type":"TinkerForge AnalogOut","z":"c0472400.26a64","device":"8952a9e3.338ef8","sensor":"vj3","name":"","x":904,"y":34,"wires":[]},{"id":"8952a9e3.338ef8","type":"TinkerForgeConfig","z":"c0472400.26a64","host":"localhost","port":"4223","name":""}]

**Comment by hardillb** [comment]
Your example flow only has one node in it (and it's config node). You need to make sure you select all the nodes you want to export. Please add a more complete example flow so I can see how you are feeding the Analog out node

**Comment by mtoko** [comment]
Apologies, 

example flow

[{"id":"9f98a3f1.b1732","type":"inject","z":"c0472400.26a64","name":"","topic":"","payload":"2.5","payloadType":"num","repeat":"","crontab":"","once":false,"x":559,"y":87,"wires":[["886a4ecd.f80ca","dc440a6c.902a48"]]},{"id":"886a4ecd.f80ca","type":"debug","z":"c0472400.26a64","name":"","active":true,"console":"false","complete":"false","x":905,"y":136,"wires":[]},{"id":"dc440a6c.902a48","type":"TinkerForge AnalogOut","z":"c0472400.26a64","device":"8952a9e3.338ef8","sensor":"vj3","name":"","x":901,"y":39,"wires":[]},{"id":"8952a9e3.338ef8","type":"TinkerForgeConfig","z":"c0472400.26a64","host":"localhost","port":"4223","name":""}]

**Comment by hardillb** [comment]
OK, found the problem, a small typo. I'll push a fix later today
