### ISSUE TITLE
RemoteSwitch.js

### ISSUE THREAD

**Issue by gfx1** [tyrrellsystems/node-red-contrib-tinkerforge#27]
In
https://github.com/tyrrellsystems/node-red-contrib-tinkerforge/blob/master/bricklets/RemoteSwitch.js
line 65 it uses
if (switchto) {
but Tinkerforge.BrickletRemoteSwitch.SWITCH_TO_OFF equals 0 so the RemoteSwitch can only turn things on (1) and not off (0)
when replacing the if statement with true so that it always runs it seems to work.

**Comment by hardillb** [comment]
Thanks for pointing this out.

There needs to be some test to check that the right type of input message was received, but we can swap that for something else.

**Comment by hardillb** [comment]
@gfx1 I don't have a remote switch module to test with, can you crab the latest code and test it before I ship a new npm.

Thanks

**Comment by gfx1** [comment]
Sorry for the late reply. The changes work.
It now clicks on and off out of the box.

Thanks.
