### ISSUE TITLE
Input and Ouputs

### ISSUE THREAD

**Issue by davidoc85** [tyrrellsystems/node-red-contrib-tinkerforge#3]
Hi,

While testing the Digital Inputs and Outputs it became apparent that it is defaulted to output/input 0, how can a different output/input be selected? (there are 4 in total)

**Comment by hardillb** [comment]
Sorry, I thought I'd done the doc for these nodes  in the sidebar.

For the input node you get a message each time a input changes state. `msg.payload` is 1 for true 0 for false. The different inputs are added to the end of the `msg.topic`.

So if you set the topic to `foo` you get `foo/0` for the first input and `foo/3` for the last

Output node takes several different formats:
1. you can set the payload of the input message to an object with keys that match the output names. e.g. this will set the first output high and the rest low
   { "0": true, "1": false, "2": false, "3": false }
   
   You have to set the state for all the outputs each time, if you don't set one it defaults to false.
2. you can pass in an array of 1/0 or true/false
   [0,1,0,0] or [false,true,false,false]
3. You can pass in a csv string 
    "1,0,0,1"
